spring:
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      web:
        client:
          enabled: true
      sampler:
        probability: 1.0
  datasource:
    url: jdbc:mysql://localhost:3306/testdemo?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: tx-server
  main:
      allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true

moduleName: tx-server

tx-lcn:
  # 配置指向TM
  client:
    manager-address: localhost:8070
  # 开启日志, 默认为false
  logger:
    enabled: true
    driver-class-name: ${spring.datasource.driver-class-name}
    jdbc-url: jdbc:mysql://localhost:3306/tx-lcn?serverTimezone=CTT&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}

logging:
  level:
    com:
      codingapi:
        txlcn: debug

server:
  port: 10001

mybatis:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

