server:
  port: 10002

spring:
  application:
    name: tx-consume
  main:
    #解决bean重复定义的。设置为true时，后定义的bean会覆盖之前定义的相同名称的bean。
    allow-bean-definition-overriding: true
  #主要功能是收集系统的时序数据，从而跟踪微服务架构的系统时序等问题。Zipkin还提供了一个非常友好的界面，来帮助分析追踪数据。
  zipkin:
    #zipkin指向路径
    base-url: http://localhost:9411
  #它在日志中引入唯一ID，以保证微服务调用之间的一致性，这样你就能跟踪某个请求是如何从一个微服务传递到下一个(监控服务调用)
  sleuth:
    web:
      client:
        enabled: true
    sampler:
      #采样率为100
      probability: 1.0
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456

  rabbitmq:
    password: guest
    username: guest
    port: 5672
    host: localhost

##配置注册中心
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:9999/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
moduleName: tx-consume

##feign熔断措施
feign:
  hystrix:
    enabled: true

##配置熔断保护
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

##配置ribbon客户端负载均衡
ribbon:
  eureka:
    enabled: true
  eager-load:
    enabled: true
    clients:
    - tx-server
    - tx-dept-server

##日志等级debug
logging:
  level:
    com:
      codingapi:
        txlcn: DEBUG

##配置tx-lcn事务
tx-lcn:
  ribbon:
    loadbalancer:
      dtx:
        enabled: true #是否采用轮询
  #指向事务监听
  client:
    manager-address: localhost:8070





